USE startersql;
SELECT * from users;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100)
);
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) UNIQUE,
name VARCHAR(100)
);
ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users DROP INDEX email;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100)
);
ALTER TABLE users AUTO_INCREMENT = 1000;